FROM mysql:5.6
ENV MYSQL_ROOT_PASSWORD root
# это не даёт возможности маппинга порта
# ф-ция expose просто даёт возможность открыть порт на контейнере, чтобы достучатьс до него из localhost
#
# EXPOSE 3306/tcp
VOLUME tmp/mysql
COPY ./sql-scripts/mysql /docker-entrypoint-initdb.d/