version: '3'
services:
  postgresql-service:
    container_name: postgresql-spring-boot-container
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: spring_boot
    expose:
      - 5432/tcp
    image: postgres:alpine
    networks:
      - backend
    ports:
      - ${POSTRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  mail-dev-service:
    container_name: mail-dev-container
    expose:
      - 25/tcp
    image: djfarrelly/maildev
    networks:
      - backend
    ports:
      - 1080:80
      - 1025:25/tcp
    restart: always
  app-service:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: app-spring-boot-container
    depends_on:
      - postgresql-service
      - mail-dev-service
    environment:
      spring.datasource.url: "jdbc:postgresql://postgresql-service:5432/spring_boot"
      spring.mail.host: "mail-dev-service"
      spring.mail.posr: "25"
    networks:
      - backend
    ports:
      - ${APP_PORT}:8080
    restart: always
networks:
  backend:
volumes:
  db-data: