application:
  jwt:
    secretKey: "secure_secure_secure_secure_secure_secure_secure_secure_secure_secure_secure_secure_secure"
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  datasource:
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show-sql: false
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
logging:
  level:
    org:
      springframework:
        security: INFO