application:
  jwt:
    secretKey: "secure_secure_secure_secure_secure_secure_secure_secure_secure_secure_secure_secure_secure"
    tokenPrefix: "Bearer "
    tokenExpirationSeconds: 86400 #31536000(for token for integration tests)
    issuer: "Spring_Demo_API_Service"

database:
  port: 5432
  host: localhost
  schema: postgres
server:
  servlet:
    context-path: /demo/api/v1/
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.schema}
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show-sql: false
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
logging:
  level:
    org:
      springframework:
        security: INFO